#!/usr/bin/env python3
"""Add the eleven town buildings to assets/meshes/manifest.json.

Every number comes from the Blender measurement reports rather than from the
sizes the generation asked for, because prepare_mesh_candidate.py is what
decides the final geometry and validate_mesh_assets.py compares the manifest
against what is actually on disk.

robloxAssetId is left null. upload_mesh_assets.py fills it in, and a null is a
visible "not uploaded yet" rather than a plausible-looking wrong number.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets/meshes/manifest.json"
REPORTS = ROOT / "meshy_output/reports"

# id -> (display name, role, the building it renders)
BUILDINGS = {
    "mesh_celebration_stage_a": (
        "Emberhollow Celebration Stage",
        "town_celebration_stage",
        "building_celebration_stage",
    ),
    "mesh_sawmill_a": ("Emberhollow Sawmill", "town_sawmill", "building_sawmill"),
    "mesh_union_forge_a": ("Union Forge", "town_forge", "building_forge"),
    "mesh_engineer_yard_a": (
        "Engineer Yard Workshop",
        "town_engineer_yard",
        "building_engineer_yard",
    ),
    "mesh_common_kitchen_a": ("Common Kitchen", "town_kitchen", "building_kitchen"),
    "mesh_hearthmarket_stalls_a": (
        "Hearthmarket Stalls",
        "town_market_stalls",
        "building_market",
    ),
    "mesh_trade_post_a": ("Emberhollow Trade Post", "town_trade_post", "building_trade_post"),
    "mesh_guardhouse_a": ("Watch Ring Guardhouse", "town_guardhouse", "building_guardhouse"),
    "mesh_watchtower_a": ("Watch Ring Watchtower", "town_watchtower", "building_watchtower"),
    "mesh_trapworks_a": ("Watch Ring Trapworks", "town_trapworks", "building_trapworks"),
    "mesh_waterworks_a": ("Greenward Waterworks", "town_waterworks", "building_waterworks"),
}

PROVENANCE = (
    "Original Last Light asset prompted from the docs/VISUAL_QUALITY_STANDARD.md style "
    "formula via the meshy-3d-generation skill: text-to-3d preview then PBR refine, "
    "generated by scripts/generate_town_buildings_parallel.sh. Normalized, decimated, and "
    "texture-downscaled to 1024 by the repository Blender pipeline. Renders "
    "{building} for the Milestone 4 sixteen-building town."
)


def main() -> int:
    manifest = json.loads(MANIFEST.read_text())
    existing = {asset["id"] for asset in manifest["assets"]}

    added = 0
    for asset_id, (display, role, building) in BUILDINGS.items():
        if asset_id in existing:
            print(f"  skip {asset_id} (already in manifest)")
            continue

        report_path = REPORTS / f"{asset_id}.json"
        if not report_path.exists():
            print(f"  MISSING report for {asset_id}", file=sys.stderr)
            return 1
        report = json.loads(report_path.read_text())

        manifest["assets"].append(
            {
                "id": asset_id,
                "displayName": display,
                "role": role,
                "placementBand": "curated_core",
                "source": "original_meshy_text_to_3d",
                "provenance": PROVENANCE.format(building=building),
                "file": f"generated/{asset_id}.glb",
                "targetLongestDimension": report["targetLongestDimension"],
                "maxTriangles": report["trianglesAfter"],
                "maxMaterialSlots": max(1, report["materialSlots"]),
                "robloxAssetId": None,
            }
        )
        added += 1
        print(
            f"  add {asset_id}: {report['targetLongestDimension']} studs, "
            f"{report['trianglesAfter']} tris, {report['materialSlots']} slot(s)"
        )

    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\n{added} added; manifest now holds {len(manifest['assets'])} assets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
