#!/usr/bin/env python3
"""Build the three release documents out of the repository.

M14's deliverable list asks for release notes, known issues and dashboards. All
three are normally written from memory at the end of a project, which is the one
moment nobody has any, and this repository has already paid for that: the whole
reason PROJECT_STATUS.md exists is that a feature was once built twice because
nothing recorded it was in flight.

So none of the three is written. Each is a projection of something the
repository already holds and already checks:

  * **RELEASE_NOTES.md** is the merged pull request stream out of git, grouped
    by the place version each one produced.
  * **KNOWN_ISSUES.md** is the open threads the handoff already keeps -- the
    paragraphs that begin **Open** or **Still owner-gated** -- lifted out of
    2,600 lines of prose and put in one list.
  * **DASHBOARDS.md** is the analytics taxonomy: every marked emitter in `src`,
    beside the gate or tuning decision it feeds.

Run it with `npm run notes` to rewrite them, and `--check` in `npm run check` to
fail when they are stale. A generated document that can go stale is a document
written from memory again, with an extra step.

Two guards matter more than the documents.

**Every pull request the handoff records has to exist in git.** A handoff citing
a number that never landed is a note about something that did not happen, and
nothing else in the project would ever notice.

**Every wave has to have a handoff entry.** The other direction cannot be
demanded of every pull request -- plenty are one-line fixes the handoff
summarised in a batch -- but a *wave* is the unit this project ships in, and the
wave plan records the pull request each one shipped as. Holding those two lists
against each other found three waves with no entry at all on the day it was
written.

**And the counts are pinned**, for the reason #336 is about: a parser that finds
nothing produces a known-issues document that reads exactly like a project with
no known issues.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
STATUS = DOCS / "PROJECT_STATUS.md"
WAVE_PLANS = ("WAVE_PLAN_M11_M14.md", "WAVE_PLAN_M8_M10.md")

# Pins. The first two are the shape of the history and move when it moves; the
# third is the one with teeth, because an empty known-issues list and a broken
# parser are the same document.
MIN_MERGED = 340
MIN_ENTRIES = 84
MIN_OPEN_THREADS = 9
MIN_EVENTS = 23

GENERATED = "<!-- Generated by scripts/generate_release_docs.py. Do not edit by hand. -->"

MERGE_SUBJECT = re.compile(r"^Merge pull request #(\d+) from \S+$")
SQUASH_SUBJECT = re.compile(r"^(.*) \(#(\d+)\)$")
ENTRY = re.compile(r"^- \*\*#(\d+)(?:[\u2013-]#?(\d+))?\*\*(?: \((v\d+)[^)]*\))?", re.M)
SHIPPED = re.compile(r"shipped #(\d+)")
MARKER = re.compile(r"\*\*(Open[^*]*|Still owner-gated[^*]*)\*\*")
EVENT_MARKER = re.compile(r"(GATE-METRIC|TUNING-METRIC|COMMERCE-EVENT): ([a-z_]+)")


def git_log() -> list[tuple[int, str, str]]:
    """Every merged pull request on the first-parent line, newest first.

    Both merge shapes are read. Some of this history was squash-merged, which
    leaves the number in a trailing `(#N)` rather than in a merge commit, and a
    reader that knew only one shape would silently lose twelve pull requests --
    including four the handoff writes about by number.
    """
    raw = subprocess.run(
        ["git", "log", "--first-parent", "--date=short", "--format=%x01%ad%x02%s%x02%b"],
        capture_output=True,
        text=True,
        check=True,
        cwd=ROOT,
    ).stdout
    out: list[tuple[int, str, str]] = []
    for chunk in raw.split("\x01"):
        if not chunk.strip():
            continue
        date, subject, body = (chunk.split("\x02", 2) + ["", ""])[:3]
        merge = MERGE_SUBJECT.match(subject.strip())
        if merge is not None:
            title = body.strip().split("\n")[0] or subject.strip()
            out.append((int(merge.group(1)), date.strip(), title))
            continue
        squash = SQUASH_SUBJECT.match(subject.strip())
        if squash is not None:
            out.append((int(squash.group(2)), date.strip(), squash.group(1)))
    return out


def status_entries() -> list[tuple[int, str | None]]:
    return [
        (int(number), version)
        for number, _last, version in ENTRY.findall(STATUS.read_text())
    ]


def recorded_pull_requests() -> set[int]:
    """Every pull request the handoff has written about.

    Some entries cover a span -- `#301-#302`, `#306-#313` -- because several
    small pull requests were one piece of work. A reader that took only the
    first number would report the rest as unrecorded waves, which is a check
    crying wolf, and a check that has to be argued with every time it fires is
    a check somebody deletes.
    """
    numbers: set[int] = set()
    for first, last, _version in ENTRY.findall(STATUS.read_text()):
        numbers.update(range(int(first), int(last or first) + 1))
    return numbers


def wave_pull_requests() -> set[int]:
    numbers: set[int] = set()
    for name in WAVE_PLANS:
        numbers |= {int(n) for n in SHIPPED.findall((DOCS / name).read_text())}
    return numbers


def open_threads() -> list[tuple[int, str, str]]:
    """Pull the handoff's open threads out of its prose.

    The handoff writes an open thread as a bold **Open** or **Still owner-gated**
    lead-in inside the entry for the wave that found it, so the pull request
    number is the entry it sits in and the thread is the rest of that paragraph.
    """
    text = STATUS.read_text()
    starts = [(m.start(), int(m.group(1))) for m in ENTRY.finditer(text)]
    threads: list[tuple[int, str, str]] = []
    for index, (start, number) in enumerate(starts):
        end = starts[index + 1][0] if index + 1 < len(starts) else len(text)
        entry = text[start:end]
        for match in MARKER.finditer(entry):
            paragraph = entry[match.start():]
            paragraph = re.split(r"\n\s*\n|\n- ", paragraph)[0]
            body = paragraph[match.end() - match.start():].strip()
            body = re.sub(r"\s*\n\s*", " ", body).lstrip(":").strip()
            kind = re.sub(r"\s+", " ", match.group(1)).strip().rstrip(":")
            threads.append((number, kind, body))
    return threads


def analytics_events() -> dict[str, dict[str, list[str]]]:
    """Every marked emitter in `src`, by family, with the file it is produced in."""
    families: dict[str, dict[str, list[str]]] = {}
    for path in sorted((ROOT / "src").rglob("*.luau")):
        for family, event in EVENT_MARKER.findall(path.read_text()):
            where = str(path.relative_to(ROOT))
            families.setdefault(family, {}).setdefault(event, [])
            if where not in families[family][event]:
                families[family][event].append(where)
    return families


def doc_tables(name: str) -> list[tuple[str, str]]:
    """Every table row in a document that names an event, as (first cell, event).

    Read cell by cell rather than with one shaped pattern, because these tables
    are not one shape: the zero-tolerance gates are two columns and the rate
    gates are four. A pattern that assumed four silently found none of the
    first, which is a dashboard document with the zero-tolerance panels quietly
    missing -- the exact failure it is generated to prevent.
    """
    rows: list[tuple[str, str]] = []
    for line in (DOCS / name).read_text().split("\n"):
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        events = [
            match.group(1)
            for cell in cells
            for match in [re.fullmatch(r"`([a-z_]+)`", cell)]
            if match
        ]
        if len(events) == 1 and cells[0] and not cells[0].startswith("`"):
            rows.append((cells[0], events[0]))
    return rows


def render_release_notes(merged: list[tuple[int, str, str]], entries: list[tuple[int, str | None]]) -> str:
    version_of = {number: version for number, version in entries if version}
    lines = [
        "# Release notes",
        "",
        GENERATED,
        "",
        "Every merged pull request, newest first, grouped by the place version it",
        "produced. This is a developer changelog rather than player patch notes:",
        "it is generated from the merge stream and from the place versions",
        "PROJECT_STATUS.md records, so it cannot be wrong about what shipped, and",
        "it cannot be written in a player's language either. Patch notes in a",
        "player's language are still the owner's, and QA_RELEASE_PLAN.md's",
        "checklist says so.",
        "",
        f"{len(merged)} merged pull requests. The version column is blank where the",
        "handoff did not record one, which is most of the history before it began",
        "publishing a place per wave.",
        "",
        "| PR | Merged | Place | Title |",
        "|---|---|---|---|",
    ]
    for number, date, title in merged:
        version = version_of.get(number, "")
        safe = title.replace("|", "\\|")
        lines.append(f"| #{number} | {date} | {version} | {safe} |")
    return "\n".join(lines) + "\n"


def render_known_issues(threads: list[tuple[int, str, str]]) -> str:
    lines = [
        "# Known issues",
        "",
        GENERATED,
        "",
        "The open threads the handoff keeps, in one list. PROJECT_STATUS.md records",
        "each one inside the entry for the wave that found it, which is the right",
        "place to write it and the wrong place to read it from: at 2,600 lines,",
        "\"what is still open\" is an archaeology question. Every row below is lifted",
        "from that file rather than remembered, so this document cannot claim an",
        "issue is closed that the handoff still describes as open.",
        "",
        "**An empty list here and a broken parser look identical**, so the generator",
        f"is pinned at a minimum of {MIN_OPEN_THREADS} threads and fails rather than",
        "producing a short one.",
        "",
        f"{len(threads)} open threads.",
        "",
        "| Found in | Kind | What is open |",
        "|---|---|---|",
    ]
    for number, kind, body in threads:
        safe = body.replace("|", "\\|")
        lines.append(f"| #{number} | {kind} | {safe} |")
    return "\n".join(lines) + "\n"


def render_dashboards(families: dict[str, dict[str, list[str]]]) -> str:
    gate_of: dict[str, list[str]] = {}
    for label, event in doc_tables("RELEASE_GATES.md"):
        gate_of.setdefault(event, []).append(label)
    decision_of = {event: label for label, event in doc_tables("BETA_TUNING.md")}

    panels = [
        (
            "GATE-METRIC",
            "Release gates",
            "One panel per gate in [RELEASE_GATES.md](RELEASE_GATES.md). Every one is a "
            "rate over instants and every one is sliced by the session pair, so each "
            "panel needs the platform class and performance tier as filters rather than "
            "as separate panels.",
        ),
        (
            "TUNING-METRIC",
            "Beta tuning",
            "One panel per decision in [BETA_TUNING.md](BETA_TUNING.md). These are not "
            "rates: a tuning number is about a stretch of play, so each panel is a "
            "distribution over attempts rather than a percentage over instants, and a "
            "single average is the one shape that hides the answer.",
        ),
        (
            "COMMERCE-EVENT",
            "Commerce",
            "One panel per event in "
            "[MONETIZATION_LIVEOPS_ANALYTICS.md](MONETIZATION_LIVEOPS_ANALYTICS.md). "
            "They are four separate events rather than one `purchase` for the reason "
            "[COMMERCE_SUPPORT.md](COMMERCE_SUPPORT.md) is organised around: \"I bought "
            "it and I do not have it\" means four different things and a merged event "
            "cannot tell them apart.",
        ),
    ]

    lines = [
        "# Dashboards",
        "",
        GENERATED,
        "",
        "The panels a release is read from, generated from the emitters that exist in",
        "`src` rather than from the events somebody remembers adding. Every row below",
        "is a marked call site, which is the same list `GateMetrics.spec`,",
        "`TuningMetrics.spec` and `CommerceAnalytics.spec` hold against their",
        "documents -- so a panel here cannot name an event nothing emits, and an",
        "emitter cannot exist with no panel to read it.",
        "",
        "**A dashboard reading zero and a dashboard reading nothing look identical to",
        "the person approving a release.** That sentence is why the emitters were built",
        "in #336 and it is why this document is generated: a panel list typed by hand",
        "is a list that quietly stops matching the game.",
        "",
        "Building the panels themselves is the owner's -- this says what each one is of.",
        "",
    ]
    for family, title, blurb in panels:
        events = families.get(family, {})
        lines += [f"## {title}", "", blurb, "", f"{len(events)} panels.", ""]
        header = "Gate" if family == "GATE-METRIC" else "Decision"
        lines += [f"| Panel | {header} | Emitted from |", "|---|---|---|"]
        for event in sorted(events):
            if family == "GATE-METRIC":
                context = "; ".join(gate_of.get(event, [])) or "session dimension"
            elif family == "TUNING-METRIC":
                context = decision_of.get(event, "")
            else:
                context = "purchase funnel"
            where = ", ".join(f"`{path.rsplit('/', 1)[-1]}`" for path in events[event])
            lines.append(f"| `{event}` | {context} | {where} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    merged = git_log()
    entries = status_entries()
    threads = open_threads()
    families = analytics_events()
    events = sum(len(family) for family in families.values())

    failures: list[str] = []

    numbers_in_git = {number for number, _date, _title in merged}
    phantom = sorted(number for number, _version in entries if number not in numbers_in_git)
    # The handoff entry for a wave is written in the pull request it describes,
    # so the newest number is legitimately not merged yet. Exactly one such
    # number is allowed and only ahead of everything that has landed; a second
    # one, or one buried in the history, is a phantom.
    if phantom and phantom == [max(phantom)] and phantom[0] > max(numbers_in_git):
        phantom = []
    if phantom:
        failures.append(
            "PROJECT_STATUS.md records pull requests git has never seen: "
            + ", ".join(f"#{n}" for n in phantom)
            + ". A handoff citing a number that never landed is a note about "
            "something that did not happen"
        )

    recorded = recorded_pull_requests()
    unrecorded = sorted(wave_pull_requests() - recorded)
    if unrecorded:
        failures.append(
            "these waves shipped and the handoff has no entry for them: "
            + ", ".join(f"#{n}" for n in unrecorded)
            + ". A wave is the unit this project ships in, and the next session "
            "reads the handoff rather than the wave plan"
        )

    for count, minimum, what in (
        (len(merged), MIN_MERGED, "merged pull requests"),
        (len(entries), MIN_ENTRIES, "handoff entries"),
        (len(threads), MIN_OPEN_THREADS, "open threads"),
        (events, MIN_EVENTS, "marked analytics events"),
    ):
        if count < minimum:
            failures.append(
                f"found {count} {what} and the generator is pinned at a minimum of "
                f"{minimum}. A parser that has stopped matching produces a short "
                f"document that reads exactly like good news"
            )

    if failures:
        print("Release document generation failed:", file=sys.stderr)
        for failure in failures:
            print(f"  * {failure}", file=sys.stderr)
        return 1

    rendered = {
        DOCS / "RELEASE_NOTES.md": render_release_notes(merged, entries),
        DOCS / "KNOWN_ISSUES.md": render_known_issues(threads),
        DOCS / "DASHBOARDS.md": render_dashboards(families),
    }

    stale: list[str] = []
    for path, content in rendered.items():
        if not args.check:
            path.write_text(content)
            continue
        if not path.is_file():
            stale.append(path.name)
        elif path.name == "RELEASE_NOTES.md":
            # The notes are allowed to lag the tip and never to be wrong. Every
            # commit that merges this file also adds a merge commit the file
            # cannot have named, so a strict compare would leave main failing
            # its own check the moment a wave lands -- and a check that fails
            # immediately after every merge is a check somebody turns off. What
            # is refused is a hole or a phantom: the rows have to be exactly the
            # tail of the merge stream ending at the newest row recorded.
            recorded_rows = re.findall(r"^\| #(\d+) \|", path.read_text(), re.M)
            if not recorded_rows:
                stale.append(path.name)
            else:
                numbers = [number for number, _date, _title in merged]
                newest = int(recorded_rows[0])
                if newest not in numbers:
                    stale.append(path.name)
                else:
                    expected = numbers[numbers.index(newest):]
                    if [int(row) for row in recorded_rows] != expected:
                        stale.append(path.name)
        elif path.read_text() != content:
            stale.append(path.name)

    if stale:
        print(
            "Release document generation failed: "
            + ", ".join(stale)
            + " is out of date. Run `npm run notes`. A generated document that can go "
            "stale is a document written from memory again, with an extra step.",
            file=sys.stderr,
        )
        return 1

    verb = "current" if args.check else "written"
    print(
        f"Release documents {verb}: {len(merged)} merged pull requests, "
        f"{len(threads)} open threads, {events} analytics panels."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
